version: "3.8"
services:
  mysql:
    image: mysql:5.7
    command: "--innodb_use_native_aio=0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Use the .env variable
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}  # Use the .env variable
    ports:
      - "3307:3306"
    volumes:
      - /var/database/docker/common:/var/lib/mysql
    networks:
      - mysqlnet

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/app
    networks:
      - mysqlnet

networks:
  mysqlnet:
    driver: bridge
